export const DETAILS_MOVIE = "MOVIE_DETAILS";
export const DETAILS_ERROR = "DETAILS_ERROR";
export const DETAILS_LOADING = "DETAILS_LOADING";

export const DETAILS_CREDITS_CAST = "DETAILS_CREDITS_CAST";
export const DETAILS_CREDITS_CREW = "DETAILS_CREDITS_CREW";
