export const FETCH_MOVIES = "FETCH_MOVIES";

export const ERROR_FETCH_MOVIES = "ERROR_FETCH_MOVIES";
export const SET_LOADER = "SET_LOADER";

export const SET_GENRES = "SET_GENRES";
export const SELECT_GENRE = "SELECT_GENRES";

export const SET_RELEASE_YEAR_START = "SET_RELEASE_YEAR_START";
export const SET_RELEASE_YEAR_END = "RELEASE_YEAR_END";

export const SORT_BY_PARAMETERS = "SORT_BY_PARAMETERS";
